### PR TITLE
Fix react duplicate keys

### PR DESCRIPTION
**Pull request by huzaifa-99**
### Details

In the E/App repo, when adding the same location multiple times for a waypoint, we would get the react duplicate keys error. This pr adds a fix for that.

### Related Issues

GH_LINK

### Manual Tests

When this branch is merged
1. In the E/App repo, go to the component where we use the MapView component
2. Add 2 waypoints that have the same coordinates (use the current location)
3. Verify you don't see the react duplicate keys error

### Linked PRs

https://github.com/Expensify/App/pull/25990

### CODE REVIEW

**Comment by huzaifa-99** [comment]
cc: @hayata-suenaga @narefyev91

**Comment by huzaifa-99** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hayata-suenaga** [comment]
I asked [the author of this PR](https://github.com/Expensify/App/pull/25977) to include this fix in their PR as we're actually closing the map library and moving all the code over to App.

**Comment by huzaifa-99** [comment]
Sounds good. Please feel free to close this PR @hayata-suenaga

**Pull request closed without merging**
